name: bitbake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '38 14 2 * *'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone bitbake
        run: git clone --depth=100 git://git.openembedded.org/bitbake

      - name: Build docs
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "bitbake/doc/"
          pre-build-command: |
            pip install sphinx_rtd_theme
            apt-get update -y && apt-get install -y texinfo
          build-command: "make info"

      - name: Build package
        run: make

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: '*.tar'
        
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
